#!/bin/bash

# Constants
standard_options=('helper' 'verbose' 'debugging' 'quiet' 'logging' 'tester' 'version' 'timelog' 'reset' 'save&quit')

function toggle () {
    echo '$1:' "$1"
    if (($1)) # Test for true
    then
    echo "$1 true"
    declare "$1"=0 # set matching varFlag to "false" ie zero
    echo "removed $1 option"
    return
    fi

    if ! (($1)) # Test for False
    then
    echo "$1 false"
    declare "$1"=1 # set matching varFlag to "true" ie one
    echo "$1"
    echo "included $1 option"
    return
    fi
    
}

## Main Loop
echo 'Shell script creation wizard v0.1'
    # read -rp 'Shabang/shell type (default: #!/bin/sh): ' shabang
    # read -rp 'Script name (default: "default"): ' name
    # read -rp 'Description (default: none): ' description
    # read -rp 'Credit/author (default: "anonymous"): ' author
    # read -rp 'License (default: none): ' license
    # read -rp 'Notes (default: none): ' notes
    echo 'Enter a number to toggle these standard options:'

    std_opts='helper verbose debugging quiet logging tester version timelog reset save&quit'
    PS3='Select : '
    select name in $std_opts
    do
        # case $std_opts in
        #     "$name")
        #     echo "$name"
        #     ;;
        # esac
        if [[ $std_opts =~ $name ]]; then
            case $name in
                quit)
                break;;
                *)
                echo "$name has not yet been implemented"
            esac
        fi    

        # "incl_$name"=       
        # if [ "$name" == 'quit' ]
        # then
        # break
        # fi
        # flip "$name"
    done

# case "$string" in 
#   *foo*)
#     
#     ;;
# esac

# string='My long string'
# if [[ $string == *"My long"* ]]; then
#   echo "It's there!"
# fi

# case expression in
#     pattern1 )
#         statements ;;
#     pattern2 )
#         statements ;;
#     ...
# esac


exit


